// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

package main

import (
	"go.opentelemetry.io/collector/otelcol"
)

func components() (otelcol.Factories, error) {
	_ = "STUB: not implemented"
	return *new(otelcol.Factories), nil
}
